import path from "../api/path";
export default {
  ...path,
  RESET_STORE_MUTATION: "RESET_STORE",
  RELOAD_CUR_PAGE: "RELOAD_CUR_PAGE",
  SET_LANGUAGE: "SET_LANGUAGE",
  GENERATE_ROUTES: "GENERATE_ROUTES",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  CLOSE_SIDEBAR: "CLOSE_SIDEBAR"
};
